version: '3'
services:
  api:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/srv/app:ro
    depends_on:
      - proxy
    environment:
      HTTP_PROXY: 'http://proxy:8081'
      # HTTPS_PROXY: 'http://host:port'
      NO_PROXY: 'localhost'

  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    command: 'php /srv/app/proxy.php'
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./:/srv/app:ro